name: BUILD_NGINX_WITH_BORINGSSL(V2)

on:
  workflow_dispatch:
    inputs:
      nginx_commit_id:
        description: "指定nginx使用commit id版本"
        required: true
        default: "release-1.27.3"
        type: string
      ssl_commit_id:
        description: "指定BoringSSL使用commit id版本"
        required: true
        default: "0.20241203.0"
        type: string
      ngx_brotli_commit_id:
        description: "指定ngx_brotli使用commit id版本"
        required: true
        default: "master"
        type: string
      ngx_headers_more_commit_id:
        description: "指定ngx_headers_more使用commit id版本"
        required: true
        default: "master"
        type: string
      njs_commit_id:
        description: "指定njs使用commit id版本"
        required: true
        default: "master"
        type: string
      build_base:
        description: "enable base build"
        default: true
        type: boolean
      build_core:
        description: "enable core build"
        default: true
        type: boolean
      release_archives:
        description: "enable release archives"
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    # 同一个标签，不能多次push，会强制清空覆盖所有数据
    # strategy:
    #   matrix:
    #     os: [linux/amd64, linux/arm64]
    steps:
      - name: Free Disk-Space
        run: df -h && sudo apt-get clean && docker system prune -a -f && sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc && df -h

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: git curl wget

      - name: init
        run: |
          cp -f ${{ github.workspace }}/conf/nginx.conf ${{ github.workspace }}/mainline/nginx.conf
          ls ${{ github.workspace }}/mainline/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push (base)
        if: ${{ inputs.build_base }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/mainline/
          file: ${{ github.workspace }}/mainline/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            NGINX_COMMIT_ID=${{ inputs.nginx_commit_id }}
            BORINGSSL_COMMIT_ID=${{ inputs.ssl_commit_id }}
            NGX_BROTLI_COMMIT_ID=${{ inputs.ngx_brotli_commit_id }}
            NGX_HEADERS_MORE_COMMIT_ID=${{ inputs.ngx_headers_more_commit_id }}
            NJS_COMMIT_ID=${{ inputs.njs_commit_id }}
          push: ${{ inputs.release_archives }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-base-boringssl
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:base-boringssl
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:base-boringssl-latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nginx:base-boringssl-latest
          cache-to: type=inline

      - name: Build And Push (core)
        if: ${{ inputs.build_core }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/mainline/
          file: ${{ github.workspace }}/mainline/Core.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            NGINX_COMMIT_ID=${{ inputs.nginx_commit_id }}-
            BORINGSSL_COMMIT_ID=${{ inputs.ssl_commit_id }}-
          push: ${{ inputs.release_archives }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ inputs.nginx_commit_id }}-${{ inputs.ssl_commit_id }}-boringssl
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:boringssl
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:boringssl-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nginx:base-boringssl-latest
          cache-to: type=inline
